/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MAIN_H_RPCGEN
#define _MAIN_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct values {
	float num1;
	float num2;
	char operation;
};
typedef struct values values;

#define compute 0x03589032
#define COMPUTE_VERSION 6

#if defined(__STDC__) || defined(__cplusplus)
#define ADD 1
extern  float * add_6(values *, CLIENT *);
extern  float * add_6_svc(values *, struct svc_req *);
#define SUB 2
extern  float * sub_6(values *, CLIENT *);
extern  float * sub_6_svc(values *, struct svc_req *);
#define DIV 3
extern  float * div_6(values *, CLIENT *);
extern  float * div_6_svc(values *, struct svc_req *);
#define MUL 4
extern  float * mul_6(values *, CLIENT *);
extern  float * mul_6_svc(values *, struct svc_req *);
extern int compute_6_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ADD 1
extern  float * add_6();
extern  float * add_6_svc();
#define SUB 2
extern  float * sub_6();
extern  float * sub_6_svc();
#define DIV 3
extern  float * div_6();
extern  float * div_6_svc();
#define MUL 4
extern  float * mul_6();
extern  float * mul_6_svc();
extern int compute_6_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_values (XDR *, values*);

#else /* K&R C */
extern bool_t xdr_values ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MAIN_H_RPCGEN */
