/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */
 #include "main.h"
 #include <stdio.h>

 float
 compute_6(char *host, float num1, float num2, char operation)
 {
	 CLIENT *clnt;
	 float  *result_1;
	 values  add_6_arg;
	 float  *result_2;
	 values  sub_6_arg;
	 float  *result_3;
	 values  div_6_arg;
	 float  *result_4;
	 values  mul_6_arg;
 
	 switch (operation) {
		 case '+':
			 add_6_arg.num1 = num1;
			 add_6_arg.num2 = num2;
			 add_6_arg.operation = operation;
			 clnt = clnt_create(host, compute, COMPUTE_VERSION, "udp");
			 if (clnt == 0) {
				 clnt_pcreateerror(host);
				 exit(1);
			 }
			 result_1 = add_6(&add_6_arg, clnt);
			 if (result_1 == (float *) NULL) {
				 clnt_perror(clnt, "call failed");
			 }
			 clnt_destroy(clnt);
			 return (*result_1);
		 case '-':
			 sub_6_arg.num1 = num1;
			 sub_6_arg.num2 = num2;
			 sub_6_arg.operation = operation;
			 clnt = clnt_create(host, compute, COMPUTE_VERSION, "udp");
			 if (clnt == 0) {
				 clnt_pcreateerror(host);
				 exit(1);
			 }
			 result_1 = sub_6(&sub_6_arg, clnt);
			 if (result_1 == (float *) NULL) {
				 clnt_perror(clnt, "call failed");
			 }
			 clnt_destroy(clnt);
			 return (*result_1);
		 case '/':
			 div_6_arg.num1 = num1;
			 div_6_arg.num2 = num2;
			 div_6_arg.operation = operation;
			 clnt = clnt_create(host, compute, COMPUTE_VERSION, "udp");
			 if (clnt == 0) {
				 clnt_pcreateerror(host);
				 exit(1);
			 }
			 result_1 = div_6(&div_6_arg, clnt);
			 if (result_1 == (float *) NULL) {
				 clnt_perror(clnt, "call failed");
			 }
			 clnt_destroy(clnt);
			 return (*result_1);
		 case '*':
			 mul_6_arg.num1 = num1;
			 mul_6_arg.num2 = num2;
			 mul_6_arg.operation = operation;
			 clnt = clnt_create(host, compute, COMPUTE_VERSION, "udp");
			 if (clnt == 0) {
				 clnt_pcreateerror(host);
				 exit(1);
			 }
			 result_1 = mul_6(&mul_6_arg, clnt);
			 if (result_1 == (float *) NULL) {
				 clnt_perror(clnt, "call failed");
			 }
			 clnt_destroy(clnt);
			 return (*result_1);
	 }
 
 #ifndef	DEBUG
	 clnt = clnt_create (host, compute, COMPUTE_VERSION, "udp");
	 if (clnt == NULL) {
		 clnt_pcreateerror (host);
		 exit (1);
	 }
 #endif	/* DEBUG */
 
	 result_1 = add_6(&add_6_arg, clnt);
	 if (result_1 == (float *) NULL) {
		 clnt_perror (clnt, "call failed");
	 }
	 result_2 = sub_6(&sub_6_arg, clnt);
	 if (result_2 == (float *) NULL) {
		 clnt_perror (clnt, "call failed");
	 }
	 result_3 = div_6(&div_6_arg, clnt);
	 if (result_3 == (float *) NULL) {
		 clnt_perror (clnt, "call failed");
	 }
	 result_4 = mul_6(&mul_6_arg, clnt);
	 if (result_4 == (float *) NULL) {
		 clnt_perror (clnt, "call failed");
	 }
 #ifndef	DEBUG
	 clnt_destroy (clnt);
 #endif	 /* DEBUG */
 }
 
 
 int
 main (int argc, char *argv[])
 {
	 char *host;
	 float num1, num2;
	 char operation;
 
	 if (argc < 2) {
		 printf ("usage: %s server_host\n", argv[0]);
		 exit (1);
	 }
	 host = argv[1];
	 printf("Enter num1: ");
	 scanf("%f", &num1);
	 printf("Enter num2: ");
	 scanf("%f", &num2);
	 printf("Enter operation (+, -, *, /): ");
	 scanf(" %c", &operation);
	 printf("Answer: %f", compute_6 (host, num1, num2, operation));
 exit (0);
 }
 